// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZt6q_CqrnM5NRLvP4lvPI5t6Uapcb9c',
    appId: '1:1010025590957:web:2ba6a8db604c2946291624',
    messagingSenderId: '1010025590957',
    projectId: 'monkey-todo-list',
    authDomain: 'monkey-todo-list.firebaseapp.com',
    storageBucket: 'monkey-todo-list.firebasestorage.app',
    measurementId: 'G-YG1K7NBDGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgLpmTV27fyN_V82R_Ltu3UGDwOHls1Fg',
    appId: '1:1010025590957:android:5de919f0bb80077a291624',
    messagingSenderId: '1010025590957',
    projectId: 'monkey-todo-list',
    storageBucket: 'monkey-todo-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChAnm1oQXLv-s8kAauTO2bK6NtwXvEqfk',
    appId: '1:1010025590957:ios:df029a499d6143ba291624',
    messagingSenderId: '1010025590957',
    projectId: 'monkey-todo-list',
    storageBucket: 'monkey-todo-list.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChAnm1oQXLv-s8kAauTO2bK6NtwXvEqfk',
    appId: '1:1010025590957:ios:df029a499d6143ba291624',
    messagingSenderId: '1010025590957',
    projectId: 'monkey-todo-list',
    storageBucket: 'monkey-todo-list.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMZt6q_CqrnM5NRLvP4lvPI5t6Uapcb9c',
    appId: '1:1010025590957:web:56438e0c96a39e14291624',
    messagingSenderId: '1010025590957',
    projectId: 'monkey-todo-list',
    authDomain: 'monkey-todo-list.firebaseapp.com',
    storageBucket: 'monkey-todo-list.firebasestorage.app',
    measurementId: 'G-ZE1ZSTM45T',
  );
}
